### ISSUE TITLE
Input/Output Error for get_monitor()

### ISSUE THREAD

**Issue by bconrad98** [droogmic/Py3Row#7]
I'm attempting to grab data from the rower in real time using Python. I'm able to do `erg.get_status()` and `erg.set_workout()`, but when I try to do `erg.get_monitor()` or `erg.get_erg()` I get the error shown below. I'm using a PM5 monitor and have updated the latest firmware to V32.

```
>>> erg.get_workout()
Traceback (most recent call last):
  File "c:\users\bsconra1\documents\src\pyrow\pyrow\pyrow.py", line 429, in send
    length = self.erg.write(self.outEndpoint, csafe, timeout=2000)
  File "C:\Users\bsconra1\AppData\Local\Programs\Python\Python38\lib\site-packages\usb\core.py", line 943, in write
    return fn(
  File "C:\Users\bsconra1\AppData\Local\Programs\Python\Python38\lib\site-packages\usb\backend\libusb1.py", line 837, in intr_write
    return self.__write(self.lib.libusb_interrupt_transfer,
  File "C:\Users\bsconra1\AppData\Local\Programs\Python\Python38\lib\site-packages\usb\backend\libusb1.py", line 920, in __write
    _check(retval)
  File "C:\Users\bsconra1\AppData\Local\Programs\Python\Python38\lib\site-packages\usb\backend\libusb1.py", line 595, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 5] Input/Output Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\users\bsconra1\documents\src\pyrow\pyrow\pyrow.py", line 270, in get_workout
    results = self.send(command)
  File "c:\users\bsconra1\documents\src\pyrow\pyrow\pyrow.py", line 433, in send
    raise ConnectionError("USB device disconected")
ConnectionError: USB device disconected
```

**Comment by droogmic** [comment]
I personally no longer have access to a PM5 to test this, sorry.

**Comment by bconrad98** [comment]
Figured out that the issue was a driver on my windows laptop side with drivers. Used [Zadig](https://www.softpedia.com/get/System/OS-Enhancements/Zadig.shtml) to update the driver from WinUSB to libusb-win32. Everything worked after that.
